SELECT TOP 500 
using 
OUTER join [JDE Customer.Designer Location] 'F1', 
           [JDE Customer.Designer Name] 'F3', 
           [Effective Date: # Item Number] 
WHERE      ( 
                      [Fiscal Time.Fiscal Week Seq Number]=363 
           AND        [JDE Sales Order Detail Effective.Item Number] IN ('0-WTCD-15', 
                                                                         '0-WTCD-18', 
                                                                         '0-WTCD-21', 
                                                                         '0-WTCD-24', 
                                                                         '0-CT15', 
                                                                         '0-CT18', 
                                                                         '0-CT24', 
                                                                         '0-CT21', 
                                                                         '0-UT15', 
                                                                         '0-UT18', 
                                                                         '0-UT24', 
                                                                         '0-UT21', 
                                                                         '0-KB15', 
                                                                         '0-KB18', 
                                                                         '0-KB24', 
                                                                         '0-KB21', 
                                                                         '0-WBT15', 
                                                                         '0-WBT18', 
                                                                         '0-TO30', 
                                                                         '0-TO36', 
                                                                         '0-TO24', 
                                                                         '0-TO21', 
                                                                         '0-TO27', 
                                                                         '0-TO33', 
                                                                         '0-TO18', 
                                                                         '0-SBL-30', 
                                                                         '0-SBL-33', 
                                                                         '0-SBL-36', 
                                                                         '0-TBR-C', 
                                                                         '0-PWB-C')) 'Effective Date: # Item Number1547503665', 
           [Effective Date: # Item Number] 
WHERE      ( 
                      [Fiscal Time.Fiscal Month]=12 
           AND        [Fiscal Time.Fiscal Year]=2017 
           AND        [JDE Sales Order Detail Effective.Item Number] IN ('0-WTCD-15', 
                                                                         '0-WTCD-18', 
                                                                         '0-WTCD-21', 
                                                                         '0-WTCD-24', 
                                                                         '0-CT15', 
                                                                         '0-CT18', 
                                                                         '0-CT24', 
                                                                         '0-CT21', 
                                                                         '0-UT15', 
                                                                         '0-UT18', 
                                                                         '0-UT24', 
                                                                         '0-UT21', 
                                                                         '0-KB15', 
                                                                         '0-KB18', 
                                                                         '0-KB24', 
                                                                         '0-KB21', 
                                                                         '0-WBT15', 
                                                                         '0-WBT18', 
                                                                         '0-TO30', 
                                                                         '0-TO36', 
                                                                         '0-TO24', 
                                                                         '0-TO21', 
                                                                         '0-TO27', 
                                                                         '0-TO33', 
                                                                         '0-TO18', 
                                                                         '0-SBL-30', 
                                                                         '0-SBL-33', 
                                                                         '0-SBL-36', 
                                                                         '0-TBR-C', 
                                                                         '0-PWB-C')) 'Effective Date: # Item Number1766037557', 
           [Effective Date: # Item Number] 
WHERE      ( 
                      [Fiscal Time.Fiscal Year]=2017 
           AND        [JDE Sales Order Detail Effective.Item Number] IN ('0-WTCD-15', 
                                                                         '0-WTCD-18', 
                                                                         '0-WTCD-21', 
                                                                         '0-WTCD-24', 
                                                                         '0-CT15', 
                                                                         '0-CT18', 
                                                                         '0-CT24', 
                                                                         '0-CT21', 
                                                                         '0-UT15', 
                                                                         '0-UT18', 
                                                                         '0-UT24', 
                                                                         '0-UT21', 
                                                                         '0-KB15', 
                                                                         '0-KB18', 
                                                                         '0-KB24', 
                                                                         '0-KB21', 
                                                                         '0-WBT15', 
                                                                         '0-WBT18', 
                                                                         '0-TO30', 
                                                                         '0-TO36', 
                                                                         '0-TO24', 
                                                                         '0-TO21', 
                                                                         '0-TO27', 
                                                                         '0-TO33', 
                                                                         '0-TO18', 
                                                                         '0-SBL-30', 
                                                                         '0-SBL-33', 
                                                                         '0-SBL-36', 
                                                                         '0-TBR-C', 
                                                                         '0-PWB-C')) 'Effective Date: # Item Number1014992742', 
           [Effective Date: # Item Number] 
WHERE      ( 
                      [JDE Sales Order Detail Effective.Item Number] IN ('0-WTCD-15', 
                                                                         '0-WTCD-18', 
                                                                         '0-WTCD-21', 
                                                                         '0-WTCD-24', 
                                                                         '0-CT15', 
                                                                         '0-CT18', 
                                                                         '0-CT24', 
                                                                         '0-CT21', 
                                                                         '0-UT15', 
                                                                         '0-UT18', 
                                                                         '0-UT24', 
                                                                         '0-UT21', 
                                                                         '0-KB15', 
                                                                         '0-KB18', 
                                                                         '0-KB24', 
                                                                         '0-KB21', 
                                                                         '0-WBT15', 
                                                                         '0-WBT18', 
                                                                         '0-TO30', 
                                                                         '0-TO36', 
                                                                         '0-TO24', 
                                                                         '0-TO21', 
                                                                         '0-TO27', 
                                                                         '0-TO33', 
                                                                         '0-TO18', 
                                                                         '0-SBL-30', 
                                                                         '0-SBL-33', 
                                                                         '0-SBL-36', 
                                                                         '0-TBR-C', 
                                                                         '0-PWB-C') 
           AND        [Fiscal Time.Fiscal Date]>=#2017-12-10 00:00:00#) 'Effective Date: # Item Number816346499', 
           [Effective Date: # Item Number] 
WHERE      [Fiscal Time.Fiscal Week Seq Number] = getvariable('FCCurrentWeekSeqNumber') 
AND        [JDE Sales Order Detail Effective.Item Number] IN ( '0-WTCD-15', 
                                                              '0-WTCD-18', 
                                                              '0-WTCD-21', 
                                                              '0-WTCD-24', 
                                                              '0-CT15', 
                                                              '0-CT18', 
                                                              '0-CT24', 
                                                              '0-CT21', 
                                                              '0-UT15', 
                                                              '0-UT18', 
                                                              '0-UT24', 
                                                              '0-UT21', 
                                                              '0-KB15', 
                                                              '0-KB18', 
                                                              '0-KB24', 
                                                              '0-KB21', 
                                                              '0-WBT15', 
                                                              '0-WBT18', 
                                                              '0-TO30', 
                                                              '0-TO36', 
                                                              '0-TO24', 
                                                              '0-TO21', 
                                                              '0-TO27', 
                                                              '0-TO33', 
                                                              '0-TO18', 
                                                              '0-SBL-30', 
                                                              '0-SBL-33', 
                                                              '0-SBL-36', 
                                                              '0-TBR-C', 
                                                              '0-PWB-C' ) 'F14', 
           [Effective Date: # Item Number] 
WHERE      [Fiscal Time.Fiscal Month] = getvariable('FCCurrentMonth') 
AND        [Fiscal Time.Fiscal Year] = getvariable('FCCurrentYear') 
AND        [JDE Sales Order Detail Effective.Item Number] IN ( '0-WTCD-15', 
                                                              '0-WTCD-18', 
                                                              '0-WTCD-21', 
                                                              '0-WTCD-24', 
                                                              '0-CT15', 
                                                              '0-CT18', 
                                                              '0-CT24', 
                                                              '0-CT21', 
                                                              '0-UT15', 
                                                              '0-UT18', 
                                                              '0-UT24', 
                                                              '0-UT21', 
                                                              '0-KB15', 
                                                              '0-KB18', 
                                                              '0-KB24', 
                                                              '0-KB21', 
                                                              '0-WBT15', 
                                                              '0-WBT18', 
                                                              '0-TO30', 
                                                              '0-TO36', 
                                                              '0-TO24', 
                                                              '0-TO21', 
                                                              '0-TO27', 
                                                              '0-TO33', 
                                                              '0-TO18', 
                                                              '0-SBL-30', 
                                                              '0-SBL-33', 
                                                              '0-SBL-36', 
                                                              '0-TBR-C', 
                                                              '0-PWB-C' ) 'F18', 
           [Effective Date: # Item Number] 
WHERE      ( 
                      [Fiscal Time.Fiscal Year] = getvariable('FCCurrentYear')) 
AND        [JDE Sales Order Detail Effective.Item Number] IN ( '0-WTCD-15', 
                                                              '0-WTCD-18', 
                                                              '0-WTCD-21', 
                                                              '0-WTCD-24', 
                                                              '0-CT15', 
                                                              '0-CT18', 
                                                              '0-CT24', 
                                                              '0-CT21', 
                                                              '0-UT15', 
                                                              '0-UT18', 
                                                              '0-UT24', 
                                                              '0-UT21', 
                                                              '0-KB15', 
                                                              '0-KB18', 
                                                              '0-KB24', 
                                                              '0-KB21', 
                                                              '0-WBT15', 
                                                              '0-WBT18', 
                                                              '0-TO30', 
                                                              '0-TO36', 
                                                              '0-TO24', 
                                                              '0-TO21', 
                                                              '0-TO27', 
                                                              '0-TO33', 
                                                              '0-TO18', 
                                                              '0-SBL-30', 
                                                              '0-SBL-33', 
                                                              '0-SBL-36', 
                                                              '0-TBR-C', 
                                                              '0-PWB-C' ) 'F20', 
           [Effective Date: # Item Number] 
WHERE      [JDE Sales Order Detail Effective.Item Number] IN ( '0-WTCD-15', 
                                                              '0-WTCD-18', 
                                                              '0-WTCD-21', 
                                                              '0-WTCD-24', 
                                                              '0-CT15', 
                                                              '0-CT18', 
                                                              '0-CT24', 
                                                              '0-CT21', 
                                                              '0-UT15', 
                                                              '0-UT18', 
                                                              '0-UT24', 
                                                              '0-UT21', 
                                                              '0-KB15', 
                                                              '0-KB18', 
                                                              '0-KB24', 
                                                              '0-KB21', 
                                                              '0-WBT15', 
                                                              '0-WBT18', 
                                                              '0-TO30', 
                                                              '0-TO36', 
                                                              '0-TO24', 
                                                              '0-TO21', 
                                                              '0-TO27', 
                                                              '0-TO33', 
                                                              '0-TO18', 
                                                              '0-SBL-30', 
                                                              '0-SBL-33', 
                                                              '0-SBL-36', 
                                                              '0-TBR-C', 
                                                              '0-PWB-C' ) 
AND        ( 
                      [Fiscal Time.Fiscal Date] >= datetime(getvariable('Yesterday'))) 'F16', 
           [Effective Date: # Item Number] 
WHERE      [JDE Sales Order Detail Effective.Item Number] IN ( '0-WTCD-15', 
                                                              '0-WTCD-18', 
                                                              '0-WTCD-21', 
                                                              '0-WTCD-24', 
                                                              '0-CT15', 
                                                              '0-CT18', 
                                                              '0-CT24', 
                                                              '0-CT21', 
                                                              '0-UT15', 
                                                              '0-UT18', 
                                                              '0-UT24', 
                                                              '0-UT21', 
                                                              '0-KB15', 
                                                              '0-KB18', 
                                                              '0-KB24', 
                                                              '0-KB21', 
                                                              '0-WBT15', 
                                                              '0-WBT18', 
                                                              '0-TO30', 
                                                              '0-TO36', 
                                                              '0-TO24', 
                                                              '0-TO21', 
                                                              '0-TO27', 
                                                              '0-TO33', 
                                                              '0-TO18', 
                                                              '0-SBL-30', 
                                                              '0-SBL-33', 
                                                              '0-SBL-36', 
                                                              '0-TBR-C', 
                                                              '0-PWB-C' ) 
AND        ( 
                      [Fiscal Time.Fiscal Date] >= datetime(getvariable('Yesterday'))) 'F30', 
           [Effective Date: # Item Number] 
WHERE      [Fiscal Time.Fiscal Week Seq Number] = getvariable('FCCurrentWeekSeqNumber') 
AND        [JDE Sales Order Detail Effective.Item Number] IN ( '0-WTCD-15', 
                                                              '0-WTCD-18', 
                                                              '0-WTCD-21', 
                                                              '0-WTCD-24', 
                                                              '0-CT15', 
                                                              '0-CT18', 
                                                              '0-CT24', 
                                                              '0-CT21', 
                                                              '0-UT15', 
                                                              '0-UT18', 
                                                              '0-UT24', 
                                                              '0-UT21', 
                                                              '0-KB15', 
                                                              '0-KB18', 
                                                              '0-KB24', 
                                                              '0-KB21', 
                                                              '0-WBT15', 
                                                              '0-WBT18', 
                                                              '0-TO30', 
                                                              '0-TO36', 
                                                              '0-TO24', 
                                                              '0-TO21', 
                                                              '0-TO27', 
                                                              '0-TO33', 
                                                              '0-TO18', 
                                                              '0-SBL-30', 
                                                              '0-SBL-33', 
                                                              '0-SBL-36', 
                                                              '0-TBR-C', 
                                                              '0-PWB-C' ) 'F31', 
           [Effective Date: # Item Number] 
WHERE      ( 
                      [Fiscal Time.Fiscal Year] = getvariable('FCCurrentYear')) 
AND        [JDE Sales Order Detail Effective.Item Number] IN ( '0-WTCD-15', 
                                                              '0-WTCD-18', 
                                                              '0-WTCD-21', 
                                                              '0-WTCD-24', 
                                                              '0-CT15', 
                                                              '0-CT18', 
                                                              '0-CT24', 
                                                              '0-CT21', 
                                                              '0-UT15', 
                                                              '0-UT18', 
                                                              '0-UT24', 
                                                              '0-UT21', 
                                                              '0-KB15', 
                                                              '0-KB18', 
                                                              '0-KB24', 
                                                              '0-KB21', 
                                                              '0-WBT15', 
                                                              '0-WBT18', 
                                                              '0-TO30', 
                                                              '0-TO36', 
                                                              '0-TO24', 
                                                              '0-TO21', 
                                                              '0-TO27', 
                                                              '0-TO33', 
                                                              '0-TO18', 
                                                              '0-SBL-30', 
                                                              '0-SBL-33', 
                                                              '0-SBL-36', 
                                                              '0-TBR-C', 
                                                              '0-PWB-C' ) 'F33', 
           [Effective Date: # Item Number] 
WHERE      [Fiscal Time.Fiscal Month] = getvariable('FCCurrentMonth') 
AND        [Fiscal Time.Fiscal Year] = getvariable('FCCurrentYear') 
AND        [JDE Sales Order Detail Effective.Item Number] IN ( '0-WTCD-15', 
                                                              '0-WTCD-18', 
                                                              '0-WTCD-21', 
                                                              '0-WTCD-24', 
                                                              '0-CT15', 
                                                              '0-CT18', 
                                                              '0-CT24', 
                                                              '0-CT21', 
                                                              '0-UT15', 
                                                              '0-UT18', 
                                                              '0-UT24', 
                                                              '0-UT21', 
                                                              '0-KB15', 
                                                              '0-KB18', 
                                                              '0-KB24', 
                                                              '0-KB21', 
                                                              '0-WBT15', 
                                                              '0-WBT18', 
                                                              '0-TO30', 
                                                              '0-TO36', 
                                                              '0-TO24', 
                                                              '0-TO21', 
                                                              '0-TO27', 
                                                              '0-TO33', 
                                                              '0-TO18', 
                                                              '0-SBL-30', 
                                                              '0-SBL-33', 
                                                              '0-SBL-36', 
                                                              '0-TBR-C', 
                                                              '0-PWB-C' ) 'F34' 
FROM       [ALL] 
WHERE      [JDE Customer.Designer Location] IS NOT NULL display BY [JDE Customer.Designer Location] ascending nulls last ,
           [JDE Customer.Designer Name] ascending nulls last